version: 0.2

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"
  parameter-store:
    LOGIN_PASSWORD: /CodeBuild/dockerLoginPassword

phases:
  install:
    commands:
      - npm install --production
      - npm install -g tsc
  build:
    commands:
      - tsc

artifacts:
  files:
    - node_modules/**/*
    - build/**/*
