service: epsilon

useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:*
          Resource:
            - "arn:aws:s3:::nurtai-pics-test/*"
            - "arn:aws:s3:::nurtai-pics-test"

functions:
  api:
    handler: src/resizer.handler
    events:
      - httpApi: '*'
    environment:
      INPUT_S3_BUCKET: ${env:INPUT_S3_BUCKET}