Description: Aspan picture repository back-end

Parameters:
  Timestamp:
    Description: Timestamp
    Type: String
    MinLength: 1
    MaxLength: 16
    AllowedPattern: "[0-9]*"
  DeploymentBucketName:
    Description: Deployment bucket name
    Type: String
    MinLength: 1
    MaxLength: 100
  AllowedExtensions:
    Description: AllowedExtensions
    Type: String
    MinLength: 1
    MaxLength: 100

Resources:
  MetaTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${AWS::StackName}-meta-table
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"

  AppsyncApi:
    Type: AWS::AppSync::GraphQLApi
    Properties:
      Name: !Sub ${AWS::StackName}-appsync
      AuthenticationType: API_KEY
  ApiKey:
    Type: AWS::AppSync::ApiKey
    DependsOn: AppsyncApi
    Properties:
      ApiId: !GetAtt AppsyncApi.ApiId
  AppsyncSchema:
    Type: AWS::AppSync::GraphQLSchema
    DependsOn: AppsyncApi
    Properties:
      ApiId: !GetAtt AppsyncApi.ApiId
      DefinitionS3Location: !Sub s3://${DeploymentBucketName}/cloudformation/schema_${Timestamp}.graphql
  MetaDataSource:
    Type: AWS::AppSync::DataSource
    DependsOn: AppsyncApi
    Properties:
      ApiId: !GetAtt AppsyncApi.ApiId
      Name:
        !Join [
          "_",
          [!Join ["_", !Split ["-", !Sub "${AWS::StackName}"]], "meta_datasource"],
        ]
      Description: "The Notes Table AppSync Data Source"
      Type: AMAZON_DYNAMODB
      ServiceRoleArn: !GetAtt DynamoDBRole.Arn
      DynamoDBConfig:
        TableName: !Ref MetaTable
        AwsRegion: !Sub ${AWS::Region}
  DynamoDBRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - Ref: AppSyncDynamoDBPolicy
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - appsync.amazonaws.com
    DependsOn:
      - AppSyncDynamoDBPolicy
  AppSyncDynamoDBPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Path: /appsync/
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:PutItem
              - dynamodb:DeleteItem
              - dynamodb:UpdateItem
              - dynamodb:Query
              - dynamodb:Scan
              - dynamodb:BatchGetItem
              - dynamodb:BatchWriteItem
            Resource: !Join ["", [!GetAtt MetaTable.Arn, "*"]]
  ListFolderLambdaAppsyncDataSource:
    Type: AWS::AppSync::DataSource
    DependsOn: ListFolderLambdaAppsyncDataSourceRole
    Properties:
      ApiId: !GetAtt AppsyncApi.ApiId
      Name:
        !Join [
          "_",
          [!Join ["_", !Split ["-", !Sub "${AWS::StackName}"]], "list_folder_datasource"],
        ]
      Type: AWS_LAMBDA
      ServiceRoleArn: !GetAtt ListFolderLambdaAppsyncDataSourceRole.Arn
      LambdaConfig:
        LambdaFunctionArn: !GetAtt ListFolderLambda.Arn
  ListFolderLambdaAppsyncDataSourceRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - !Ref ListFolderLambdaAppsyncDataSourceRolePolicy
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - appsync.amazonaws.com
  ListFolderLambdaAppsyncDataSourceRolePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Path: /appsync/
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - lambda:invokeFunction
            Resource:
              - !GetAtt ListFolderLambda.Arn
              - !Join [":", [!GetAtt ListFolderLambda.Arn, "*"]]
  ListFolderQueryResolver:
    Type: "AWS::AppSync::Resolver"
    DependsOn: AppsyncSchema
    Properties:
      ApiId: !GetAtt AppsyncApi.ApiId
      TypeName: Query
      FieldName: listFolder
      DataSourceName: !GetAtt ListFolderLambdaAppsyncDataSource.Name
  GetMetaQueryResolver:
    Type: "AWS::AppSync::Resolver"
    DependsOn: AppsyncSchema
    Properties:
      ApiId: !GetAtt AppsyncApi.ApiId
      TypeName: Query
      FieldName: getMeta
      DataSourceName: !GetAtt MetaDataSource.Name
      RequestMappingTemplate: |
        {
          "version": "2017-02-28",
          "operation": "GetItem",
          "key": {
            "id": $util.dynamodb.toDynamoDBJson($ctx.args.id)
          },
        }
      ResponseMappingTemplate: |
        $util.toJson($context.result)
  UpdateAttributesMutationResolver:
    Type: "AWS::AppSync::Resolver"
    DependsOn: AppsyncSchema
    Properties:
      ApiId: !GetAtt AppsyncApi.ApiId
      TypeName: Mutation
      FieldName: updateAttributes
      DataSourceName: !GetAtt MetaDataSource.Name
      RequestMappingTemplate: |
        {
          "version": "2017-02-28",
          "operation": "UpdateItem",
          "key": {
            "id": $util.dynamodb.toDynamoDBJson($ctx.args.id)
          },
          "update": {
            "expression": "SET attributes = :attributes",
            "expressionValues": {
              ":attributes" : $util.dynamodb.toDynamoDBJson($ctx.args.attributesInput.attributes)
            }
          }
        }
      ResponseMappingTemplate: |
        $util.toJson($context.result)
  DeleteAttributesMutationResolver:
    Type: "AWS::AppSync::Resolver"
    DependsOn: AppsyncSchema
    Properties:
      ApiId: !GetAtt AppsyncApi.ApiId
      TypeName: Mutation
      FieldName: deleteAttributes
      DataSourceName: !GetAtt MetaDataSource.Name
      RequestMappingTemplate: |
        {
          "version": "2017-02-28",
          "operation": "UpdateItem",
          "key": {
            "id": $util.dynamodb.toDynamoDBJson($ctx.args.id)
          },
          "update": {
            "expression": "REMOVE attributes"
          }
        }
      ResponseMappingTemplate: |
        $util.toJson($context.result)
  UpdateTagsMutationResolver:
    Type: "AWS::AppSync::Resolver"
    DependsOn: AppsyncSchema
    Properties:
      ApiId: !GetAtt AppsyncApi.ApiId
      TypeName: Mutation
      FieldName: updateTags
      DataSourceName: !GetAtt MetaDataSource.Name
      RequestMappingTemplate: |
        {
          "version": "2017-02-28",
          "operation": "UpdateItem",
          "key": {
            "id": $util.dynamodb.toDynamoDBJson($ctx.args.id)
          },
          "update": {
            "expression": "SET tags = :tags",
            "expressionValues": {
              ":tags" : $util.dynamodb.toDynamoDBJson($ctx.args.tagsInput.tags)
            }
          }
        }
      ResponseMappingTemplate: |
        $util.toJson($context.result)
  DeleteTagsMutationResolver:
    Type: "AWS::AppSync::Resolver"
    DependsOn: AppsyncSchema
    Properties:
      ApiId: !GetAtt AppsyncApi.ApiId
      TypeName: Mutation
      FieldName: deleteTags
      DataSourceName: !GetAtt MetaDataSource.Name
      RequestMappingTemplate: |
        {
          "version": "2017-02-28",
          "operation": "UpdateItem",
          "key": {
            "id": $util.dynamodb.toDynamoDBJson($ctx.args.id)
          },
          "update": {
            "expression": "REMOVE tags"
          }
        }
      ResponseMappingTemplate: |
        $util.toJson($context.result)

  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub ${AWS::StackName}-media
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: true
  S3BucketRule:
    DependsOn: S3Bucket
    Type: AWS::Events::Rule
    Properties:
      Description: Rule to invoke ExifLambda when new media file is uploaded
      EventPattern:
        source:
          - aws.s3
        detail-type:
          - Object Created
        detail:
          bucket:
            name:
              - !Ref S3Bucket
      State: "ENABLED"
      Targets:
        - Arn: !GetAtt ExifLambda.Arn
          Id: ExifLambdaTarget
  PermissionForEventsToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName:
        Ref: ExifLambda
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: !GetAtt S3BucketRule.Arn

  ExifLambda:
    DependsOn: AllLambdasExecutionRole
    Type: AWS::Lambda::Function
    Properties:
      Runtime: nodejs14.x
      Role: !GetAtt AllLambdasExecutionRole.Arn
      Handler: build/lambda/exif/exif.handler
      Code:
        S3Bucket: !Ref DeploymentBucketName
        S3Key: !Sub ${AWS::StackName}-${Timestamp}.zip
      Environment:
        Variables:
          TABLE_NAME: !Ref MetaTable
          ALLOWED_EXTENSIONS: !Sub ${AllowedExtensions}
  ExifLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn: ExifLambda
    Properties: 
      RetentionInDays: 14
      LogGroupName: !Join ["", ["/aws/lambda/", !Ref ExifLambda]]

  ListFolderLambda:
    DependsOn: AllLambdasExecutionRole
    Type: AWS::Lambda::Function
    Properties:
      Runtime: nodejs14.x
      Role: !GetAtt AllLambdasExecutionRole.Arn
      Handler: build/lambda/fs/listFolder.handler
      Code:
        S3Bucket: !Ref DeploymentBucketName
        S3Key: !Sub ${AWS::StackName}-${Timestamp}.zip
      Environment:
        Variables:
          MEDIA_BUCKET: !Ref S3Bucket
          ALLOWED_EXTENSIONS: !Sub ${AllowedExtensions}
  ListFolderLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn: ListFolderLambda
    Properties: 
      RetentionInDays: 14
      LogGroupName: !Join ["", ["/aws/lambda/", !Ref ListFolderLambda]]

  ResizerLambda:
    DependsOn: AllLambdasExecutionRole
    Type: AWS::Lambda::Function
    Properties:
      Runtime: nodejs14.x
      Role: !GetAtt AllLambdasExecutionRole.Arn
      Handler: build/lambda/resizer/resizer.handler
      Timeout: 10
      Code:
        S3Bucket: !Ref DeploymentBucketName
        S3Key: !Sub ${AWS::StackName}-${Timestamp}.zip
      Environment:
        Variables:
          MEDIA_BUCKET: !Ref S3Bucket
  ResizerLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn: ResizerLambda
    Properties: 
      RetentionInDays: 14
      LogGroupName: !Join ["", ["/aws/lambda/", !Ref ResizerLambda]]

  AllLambdasExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:*
                Resource: arn:aws:logs:*:*:*
              - Effect: Allow
                Action:
                  - s3:*
                Resource:
                  - !GetAtt S3Bucket.Arn
                  - !Join
                    - "/"
                    - - !GetAtt S3Bucket.Arn
                      - "*"
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                Resource: !GetAtt MetaTable.Arn

Outputs:
  ApiId:
    Value: !GetAtt AppsyncApi.ApiId
  Arn:
    Value: !GetAtt AppsyncApi.Arn
  GraphQLUrl:
    Value: !GetAtt AppsyncApi.GraphQLUrl
