version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14.x
    commands:
      - npm install
  build:
    commands:
      - printenv
      - npm run build
      - ls -la
      - npm run sam:deploy
