version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14.x
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - npm run sam:deploy
      # - sam package --resolve-s3 --template-file infrastructure/template.yaml --output-template-file packaged-template.yaml
      # - sam publish --template packaged.yaml --region us-east-1