version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14.x
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - printenv | sort
      - . scripts/env.sh
      - printenv | sort
      - sam deploy --template-file infrastructure/template.yaml --stack-name $ASPAN_APP_STACK_NAME --capabilities CAPABILITY_IAM --resolve-s3
      - sam package --resolve-s3 --template-file infrastructure/template.yaml --output-template-file packaged-template.yaml
      - sam publish --template packaged.yaml --region us-east-1