Description: pipeline

Parameters:
  ProjectName:
    Description: Project name
    Type: String
    Default: epsilon
  EnvironmentName:
    Description: Environment name, same as GitHub branch name
    Type: String
    Default: development
  FullRepositoryId:
    Type: String
    Default: "anurtayev/epsilon"

Resources:
  AppPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub ${ProjectName}-${EnvironmentName}-pipeline
      RoleArn: !ImportValue CodePipelineExecutionRoleArn
      Stages:
        - Name: Source
          Actions:
            - Name: SourceCodeRepo
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: 1
                Provider: CodeStarSourceConnection
              OutputArtifacts:
                - Name: SourceAsZip
              Configuration:
                BranchName: !Ref EnvironmentName
                ConnectionArn: !ImportValue CodeStarConnectionArn
                FullRepositoryId: !Ref FullRepositoryId
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              InputArtifacts:
                - Name: SourceAsZip
              Configuration:
                ProjectName: !Ref CodeBuildProject
        - Name: Deploy
          Actions:
            - Name: DeployProject
              InputArtifacts:
                - Name: ConnectorToDeploy
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: S3
              Configuration:
                BucketName: !ImportValue InfrastructureBucketName
                Extract: true
              RunOrder: 1
            - Name: UpdateCodePipeline
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              InputArtifacts:
                - Name: BuildOutput
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: !Ref ConnectorPipelineStackName
                TemplatePath: BuildOutput::pipeline.yaml
                ParameterOverrides: !Sub |
                  {
                    "BranchName": "${BranchName}",
                    "Stage": "${Stage}",
                    "RepositoryName": "${RepositoryName}",
                    "GithubUser": "${GithubUser}",
                    "ConnectorName": "${ConnectorName}",
                    "ConnectorPipelineStackName": "${ConnectorPipelineStackName}",
                    "Environment": "${Environment}"
                  }
                RoleArn: !ImportValue CodePipelineCFNRoleArn
              RunOrder: 2
      ArtifactStore:
        Type: S3
        Location: !ImportValue InfrastructureBucketName

  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ${ConnectorName}-${Stage}
      ServiceRole: !ImportValue CodeBuildRoleArn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
        EnvironmentVariables:
          - Name: ACCOUNT_ID
            Value: !Ref AWS::AccountId
          - Name: CONNECTOR_NAME
            Value: !Ref ConnectorName
          - Name: CONNECTOR_REPO
            Value: !Ref RepositoryName
          - Name: ENVIRONMENT
            Value: !Ref Environment
          - Name: GITHUB_BRANCH
            Value: !Ref BranchName
          - Name: GITHUB_OWNER
            Value: !Ref GithubUser
          - Name: REGION
            Value: !Ref AWS::Region
          - Name: STAGE
            Value: !Ref Stage
      Source:
        Type: CODEPIPELINE
        BuildSpec: infrastructure/buildspec.yaml
      TimeoutInMinutes: 5
